### ISSUE TITLE
[Tuist] Modular Architecture 재구성

### ISSUE THREAD

**Issue by ValseLee** [ValseLee/TCA_Yu-Gi-Oh#6]
### 📝 작업 목적

1. Feature, Interface // CommonUI, Core, Util 구조 정리
2. Test Target은 제외

### 🚩 Disclaimer
- App에 가까워질수록 구현도는 구체화된다.
- Core에 가까워질수록 구현도는 추상화된다.
- Core는 App의 구체화에 관심이 없다.

---

### 🛠️ Tasks

* [ ] App
    * [ ] Resource
* [ ] Feature 목록과 각 기능 정리
    * [x] Chat
    * [x] Login
    * [x] Feature는 각 Interface에 의존적

* [x] CommonUI
    * [x] DesignSystem
* [x] Core
    * [x] API와 plist를 보관
    * [x] Firebase
* [x] Util
    * [x] Extension
    * [x] Logger
